### ISSUE TITLE
[feat] 이전 정산 내역 쿼리 사용 

### ISSUE THREAD

**Issue by jiohjung98** [CoolPeace-yanolza/frontend#104]
## Description

이전 정산 내역 api 호출 부분 쿼리 사용해서 수정할 예정입니다.
이 외에 여러 작은 기능적 문제 및 디자인적 문제 수정할 예정입니다.

## Todo

- [x] 이전 정산 내역 api 쿼리 사용
- [x] 정산 내역 날짜 기준으로 불러오기
- [x] 숙소 변경 시, 페이지네이션 초기화 처리
- [x] 정산 내역 일자에 맞게 불러오는 작업
- [x] startDate 설정 시, 하루 밀리는 문제(ex: 2023 04월로 설정하면 2023-04-01로 설정되지 않고 2023-03-31로 설정) 작업
- [x] 팝업 컴포넌트 수정
- [x] 이전 정산 내역 레이아웃 살짝 밀리는 문제 작업
- [x] DatePicker 날짜 잘못 선택 시 경고 모달 수정
- [x] DatePicker 안에 캘린더 아이콘 삽입
- [x] 정산관리 아이콘 변경
- [x] 이전 정산 내역 에러페이지 재디자인
- [ ] 드롭다운 텍스트 위치 조정
- [ ] 엑셀 다운로드 시 정산 요약 내역 추가
