### ISSUE TITLE
[design] 대시보드 페이지 레이아웃

### ISSUE THREAD

**Issue by turkey-kim** [CoolPeace-yanolza/frontend#11]
## Description

![스크린샷 2024-01-11 오후 4 42 59](https://github.com/CoolPeace-yanolza/frontend/assets/83493231/71bbeb9b-c8be-4b21-8f77-1fd05beb3895)

## Todo

- [ ] 대시보드페이지 레이아웃 -> 구조만 잡을 예정
       (디자인 시안 1/9 오전 중에 나올 예정)
- [ ] chartJS 설치 + 그래프 테스트

## Next Issue
- [ ] 그래프 적용 (API 연동)
- [ ] 추천쿠폰 3순위 섹션 구현 (API 연동)
- [ ] 쿠폰현황 섹션 구현 (API 연동)
- [ ] 에러처리
