### ISSUE TITLE
fix: 대시보드 QA 수정사항 반영

### ISSUE THREAD

**Issue by turkey-kim** [CoolPeace-yanolza/frontend#111]
## Description

대시보드 QA 수정사항 반영

## Todo

- [x] 월별차트 카테코리 UI 표시
- [x] 쿠폰 현황 소숫점 문제
- [x] 대시보드 우측섹션 너비 고정
- [x] 그래프 업데이트 문구 수정
- [x] Top3 쿠폰 현황 하이라이팅 추가
- [x] 그래프, 데일리리포트 레이아웃 사이즈 통일
