### ISSUE TITLE
[fix] 누적 리포트 QA 이슈 해결

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#112]
## Description

1월 25일에 진행된 QA에서 나온 수정사항을 반영할 예정입니다.

## Todo

- [x] 누적 똑똑현황 소제목 컬러 변경
- [x] 누적리포트 테이블 제목(텍스트) 중앙 정렬
- [ ] 모바일 사이드바 열리지 않음 (test1 진행중)
- [ ] 사이드바 [정산관리] 아이콘 수정 요청 (재요청중)
- [x] [사업체명] 드롭다운 미표시 현상
