### ISSUE TITLE
[feat] 정산 요약 내역 엑셀 추가

### ISSUE THREAD

**Issue by jiohjung98** [CoolPeace-yanolza/frontend#114]
## Description

![image](https://github.com/CoolPeace-yanolza/frontend/assets/104253583/b6f52615-55d5-4ad9-b232-5a96cc5d9ced)
엑셀 다운로드 시, 위 사진처럼 정산 요약 내역 추가 작업((어렵네요....)

## Todo

- [x] 이전 정산 내역 키값 영어 -> 한글 변경
- [x] 엑셀 다운로드 시 정산 요약 내역 추가
- [x] 드롭다운 텍스트 위치 조정
- [ ] 페이지 이동할 때 loading 화면이 너무 짧게 나와서 깜빡이는것처럼 보이는 현상
- [x] 이전 정산 내역 로딩 및 에러 컴포넌트 크기 조정

QA
- [x] 전 달 정산 내역 UX 변경(매월 11일 업데이트 -> 매월 1일 업데이트)
- [x] 모바일 환경에서 캘린더 텍스트 색상 파란색으로 설정되는 부분 해결(배포 후 확인 필요함)
- [x] 드롭다운 텍스트 쿠폰 사용일 최근 순 -> 쿠폰 적용일 최근 순으로 변경
- [x] 팝업 텍스트 구폰 적용일 -> 쿠폰 적용일로 변경
- [x] 조회 기간 설정 시, 페이지네이션 초기화 안되는 문제 해결
