### ISSUE TITLE
[fix] 누적 리포트 QA 추가 이슈 수정

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#119]
## Description

누적 리포트 QA 추가 이슈를 수정할 예정입니다.

## Todo

- [x] 모바일-[사이드바] 열리지 않음 (test2)
- [x] 모바일-상단 프로필 아이콘 밑에 -표시 (test1)
- [x] 로그아웃 영역 마우스 호버시 커서 변경
