### ISSUE TITLE
[design] 정산관리 페이지 레이아웃

### ISSUE THREAD

**Issue by jiohjung98** [CoolPeace-yanolza/frontend#12]
## Description

<img width="713" alt="image" src="https://github.com/CoolPeace-yanolza/frontend/assets/104253583/d83f65e3-0d10-4464-9f33-258363227f14">

정산관리 페이지 레이아웃 작업

## Todo
- [ ] 정산 내역 부분
- [ ] 기간 설정 부분(캘린더)
- [ ] 정산 예정 금액 부분
- [ ] 지난달 정산 금액 부분
