### ISSUE TITLE
[fix] 사이드바 모바일 스타일 수정

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#125]
## Description

모바일 환경에서 사이드바 스타일을 일부 변경할 예정입니다.

## Todo

- [x] leftover 스타일 변경
- [x] 로그아웃 애니메이션 속도 증가
- [ ] url 이동시 배경색 변경하기
