### ISSUE TITLE
[fix] 정산페이지 QA 추가 문제

### ISSUE THREAD

**Issue by jiohjung98** [CoolPeace-yanolza/frontend#127]
## Description

- 정산페이지 헤더 아이콘 변경 예정입니다.
- 로딩페이지가 짧게 깜빡이는 문제 검토해볼 예정입니다.
- 팝업 외부 클릭 시 팝업 닫는 기능을 추가할 예정입니다.

## Todo
- [x] 정산페이지 헤더 아이콘 변경
- [x] 팝업 외부 클릭 시, 팝업 닫기
- [x] 로딩페이지 짧게 깜빡이는 문제
