### ISSUE TITLE
[fix] 등록 페이지 QA 수정사항 반영

### ISSUE THREAD

**Issue by ovoxiix** [CoolPeace-yanolza/frontend#134]
## Description
등록 페이지 QA 이후 수정사항을 반영할 예정입니다.

## Todo
- [x] 최대 할인 금액 / 2박 이상 적용 체크박스 아이콘 수정
- [x] 선택 객실 모달 체크박스, 닫기 아이콘 수정
- [x] 아코디언 토글 아이콘 수정
- [x] 쿠폰 할인 설정 유효성 메시지 수정
- [x] 미리보기 선택 객실 단어 수정
