### ISSUE TITLE
[chore] tanStack-query, recoil, react-error-boundary 세팅

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#14]
## Description

tanStack-query, recoil, react-error-boundary 설치 및 초기 세팅을 진행할 예정입니다.

## Todo

- [x] tanStack-query 초기 세팅
- [x] recoil 초기 세팅
- [x] react-error-boundary 초기 세팅
