### ISSUE TITLE
[design] 등록 페이지 반응형 디자인

### ISSUE THREAD

**Issue by ovoxiix** [CoolPeace-yanolza/frontend#142]
## Description
등록 페이지의 반응형 화면을 디자인할 예정입니다.

## Todo
- [x] 등록 페이지 반응형 디자인
- [x] 객실 선택 모달 반응형 디자인
- [x] 등록 완료 모달 반응형 디자인
