### ISSUE TITLE
[feat] 레이아웃 피드백 반영

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#15]
## Description

기획이 확정된 footer를 추가하고 PM분들에게 받은 사이드바와 헤더 피드백을 반영할 예정입니다.

## Todo
- [x] rem -> px util 함수 추가
- [x]  사이드 바 쿠폰 메뉴 토글 클릭 시 180도 회전하는 애니메이션 추가
- [x]  사이드 바 파란색 배경에의해 아이콘이 보이지 않는 현상
- [x]  헤더 유저 프로필 아이콘 교체
