### ISSUE TITLE
[feat] 헤더 선택 숙소 state Recoil atoms로 전달하기 (로그인 구현 전 버전)

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#20]
## Description

<img width="309" alt="image" src="https://github.com/CoolPeace-yanolza/frontend/assets/101972330/ff325963-5a8a-4a7f-85ce-512d6225b9c9">

헤더에서 선택된 숙소에 따라서 페이지가 바뀔 것 같아, recoil atoms 활용하여 state 전달 드리려고 합니다.

[헤더에서 숙박업소 목록 조회 시 응답 데이터]
id: 숙소ID
name: 숙소 이름

전달 받은 숙소ID를 recoil atoms state로 넣어둘 예정입니다.

## Todo

- [x] 목업 데이터로 숙소ID 가져오기 (로그인 구현 이후 API 작업)
- [x] src/recoil/headerAccomodationState.ts 파일에 atom 생성 후 숙소ID 담기
- [x] 새로고침 시에도 리코일 값 유지
