### ISSUE TITLE
[feat] 헤더 유저 프로필 클릭 시 모달 생성

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#21]
## Description

헤더 유저 프로필 클릭 시 모달을 생성할 예정입니다.
<img width="385" alt="image" src="https://github.com/CoolPeace-yanolza/frontend/assets/101972330/46ed6478-7940-4408-9f86-1c58e658afea">

## Todo

- [x] 모달 레이아웃 작업
- [x] cooki에서 user 정보 불러와 화면에 보여주기 (로그인 구현 이후에 작업)
- [x] 로그아웃 버튼 생성
- [x] 타입 정리
