### ISSUE TITLE
[doc] 1차 야놀자 멘토링 제출용 리드미 작성

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#24]
## Description

<img width="619" alt="image" src="https://github.com/CoolPeace-yanolza/frontend/assets/101972330/0e41e51d-aa41-46fd-a7c0-496104766919">

## Todo

- [ ] 해당 깃헙 메인 브랜치를 보면 되는 것인지 작성
- [ ] 대략 어떤 내용이 구현되고 있는지 작성
- [ ] 어떤 부분 피드백 받고 싶은지 작성
