### ISSUE TITLE
[design] 대시보드페이지 상세레이아웃

### ISSUE THREAD

**Issue by turkey-kim** [CoolPeace-yanolza/frontend#28]
## Description
<img width="652" alt="스크린샷 2024-01-14 오후 6 59 16" src="https://github.com/CoolPeace-yanolza/frontend/assets/83493231/c374a490-02ca-4b3f-b906-11318fc35f06">

## Todo

현재 나온 기능별 상세 레이아웃 진행
- [x] 그래프 섹션 진행
- [x] 현황 섹션 진행
- [x] 일간리포트 센션 진행
- [x] 지역구 TOP3 섹션 진행 (하단 우측)
- [x] 지역 사장님 비교 섹션 진행 (하단 좌측)
