### ISSUE TITLE
[modify] barrel (배럴) 파일 컨벤션 추가 및 일부 주요 폴더 이동

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#3]
### 배럴 파일이란
JavaScript(또는 TypeScript)에서 배럴 파일은 여러 모듈의 내보내기를 단일 import 문을 사용하여 가져올 수 있는 편리한 단일 모듈로 통합하는 방법입니다.

## Todo
배럴 파일 컨벤션을 아래 Todo에 작성된 폴더에 상황에 맞게 적용할 예정입니다.
- [x] components index.tsx 파일 추가 (리액트 컴포넌트를 반환하므로 lib 폴더를 사용하지 않습니다.)
- [x] hooks lib 폴더 추가
- [x] pages index.tsx 파일 추가 (리액트 컴포넌트를 반환하므로 lib 폴더를 사용하지 않습니다.)
- [x] routes lib 폴더 삭제 (리액트 컴포넌트를 반환하므로 lib 폴더를 사용하지 않습니다.)
- [x] styles의 경우 반환 값이 다양하고 추가될 파일이 많지 않아 barrel 파일 방식을 사용하지 않습니다.
- [x] types의 경우 d.ts 확장자를 사용하므로 따로 export를 사용하지 않아, barrel 파일 방식을 사용하지 않습니다.
- [x] api, constants src/ 로 이동 후 lib 폴더 추가
- [x] test src/ 로 이동
- [x] hooks/queries 폴더 추가 생성 (react-query hooks 관리용 파일입니다.
