### ISSUE TITLE
[design] 쿠폰대기, 만료 , 중지 레이아웃 & 카테고리 탭 구현

### ISSUE THREAD

**Issue by jinjoo-jung** [CoolPeace-yanolza/frontend#33]
## Description
- 쿠폰 조회 페이지 내에서 쿠폰 종류 디자인 추가, 객실 리스트, 카테고리 구현 디자인 예정입니다 

## Todo

- [ ] 쿠폰아이템 중 대기, 만료, 중지 쿠폰 레이아웃 추가 작업
- [ ] 페이지 탭 클릭시 디자인 변경
- [ ] 쿠폰 내에서 객실( 전체 / 일부객실 / 특정객실 ) 리스트 작업
