### ISSUE TITLE
[feat] 로그인/회원가입 페이지 추가 레이아웃

### ISSUE THREAD

**Issue by dabin-Hailey** [CoolPeace-yanolza/frontend#34]
## Description

기본 레이아웃에서 작업하지 못한 사항들을 작업합니다.

1. 입력하는 데이터의 유형 및 유효성에 따른 공통 input 컴포넌트 제작
_*유형 : 일반 텍스트 or 비밀번호
*유효성 : 검사 통과 or 실패_

![회원가입 입력필드 (1)](https://github.com/CoolPeace-yanolza/frontend/assets/139190686/aad385e0-2320-4cf0-87a8-45c34a68e395)

2. 공통 button 제작
![button](https://github.com/CoolPeace-yanolza/frontend/assets/139190686/b5af970d-0bee-47ae-b5dc-793ce17af341)

3. 로그인 실패 시 보여줄 alert 모달 제작
![로그인 _ 에러](https://github.com/CoolPeace-yanolza/frontend/assets/139190686/2950b35b-5678-46bc-b9c8-a92824617e08)

4. 회원가입 완료 페이지
![회원가입_회원가입 완료](https://github.com/CoolPeace-yanolza/frontend/assets/139190686/39123876-157c-4fd9-b76c-859f7b090d68)

## Todo

- [x] 한번에 지우기 기능이 있는 input
- [x] 한번에 지우기 + 비밀번호 미리 보기/숨기기 기능이 있는 input
- [x] 유효성 체크 아이콘이 있는 input
- [x] 유효성 체크  + 비밀번호 미리 보기/숨기기 기능이 있는 input
- [x] 기존 입력 폼에 있던 input -> 공통 input으로 변경
- [x] 공통 button 제작
- [ ] 로그인 실패 시 보여줄 alert 모달 제작
- [ ] 회원가입 완료 페이지
