### ISSUE TITLE
[design] 사이드바, 헤더 및 대시보드 모바일 반응형 레이아웃

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#40]
## Description

아래 모바일 화면에 맞게 컴포넌트를 재배치할 예정입니다.
<img width="297" alt="image" src="https://github.com/CoolPeace-yanolza/frontend/assets/101972330/216c34ec-eea9-46f0-843f-48aff795ae17">

## Todo

- [ ] 사이드바 및 헤더 모바일 반응형 화면 구현
- [ ] 반응형에 맞는 비율 스타일링 적용 (예시 : width: vw, height: calc(vw / 비율))
- [ ] 대시보드 반응형 화면 구현
