### ISSUE TITLE
[feat] 로그인 성공 시 쿠키 저장

### ISSUE THREAD

**Issue by dabin-Hailey** [CoolPeace-yanolza/frontend#43]
## Description

로그인 결과를 쿠키에 저장하는 로직을 작성합니다.

## Todo

- [x] axios 설치
- [x] axios instance 생성
- [x] setCookie, getCookie 함수 생성
- [x] 로그인 결과 쿠키에 저장
