### ISSUE TITLE
[feat] 대시보드 페이지, 우측 섹션 API연결

### ISSUE THREAD

**Issue by turkey-kim** [CoolPeace-yanolza/frontend#44]
## Description

![스크린샷 2024-01-21 오전 12 31 52](https://github.com/CoolPeace-yanolza/frontend/assets/83493231/b57136a8-a07a-4a3b-b813-9f6c47b835b7)

## Todo

- [x] 이번 달 똑똑현황, 일간 리포트 API 연결 (suspense 적용)
- [x] 대시보드 API 추가 (연결 X)
- [x] 대시보드 레이아웃 추가 수정
  - [x]  그래프 굵기
  - [x]  y2축 제거
  - [x]  애니메이션
  - [x]  다운로드리포트 텍스트 깨짐 수정
