### ISSUE TITLE
[feat] 유저 모달 cookie 정보 사용 및 개선

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#54]
## Description

유저 모달에 사용되는 API를 연결할 예정입니다.

## Todo

- [x] cookie에서 사용자 정보 가져와 렌더링하기
- [x] 모달 외 화면 클릭 시 닫힘
- [x] 로그아웃 span 너비 추가
