### ISSUE TITLE
[feat] 정산페이지 api 작업 및 레이아웃 작업

### ISSUE THREAD

**Issue by jiohjung98** [CoolPeace-yanolza/frontend#70]
## Description

- 정산 내역 api 작업
- 레이아웃 추가 작업

## Todo

- [x] 지난 정산 조회 api
- [x] 정산 조회 요약 api 
- [x] 셀렉터(드롭다운) 디자인 추가 작업
- [ ] 캘린더 디자인 변경안 확정 시 디자인 추가 작업(color, border-radius, selectColor)
- [ ] 팝업 컴포넌트 전체적인 레이아웃 재작업 및 위치 수정
