### ISSUE TITLE
[feat] 대시보드 api 연동(2)

### ISSUE THREAD

**Issue by turkey-kim** [CoolPeace-yanolza/frontend#76]
## Description

대시보드 API 추가 연동

## Todo

- [x] 월별 리포트 그래프 API 연동
- [x] 다운로드리포트 API 연동
- [x] 지역숙소 현황 API 연동
