### ISSUE TITLE
[design] 로그인,회원가입 페이지 레이아웃

### ISSUE THREAD

**Issue by dabin-Hailey** [CoolPeace-yanolza/frontend#8]
## Description

피그마에 따라 로그인,회원가입 페이지의 레이아웃을 작업합니다.

</br>

### 로그인 기본 레이아웃
![로그인 기본 (1)](https://github.com/CoolPeace-yanolza/frontend/assets/139190686/80717142-f678-4790-a715-4c3580f8bed1)

### 회원가입 기본 레이아웃
![회원가입 기본](https://github.com/CoolPeace-yanolza/frontend/assets/139190686/44f38c75-c4a9-4021-8595-77d539e35fe7)

</br>

## Todo

- [x] 로그인 페이지 마크업
- [x] 로그인 페이지 디자인
- [x] 회원가입 페이지 마크업
  - [x] input form 생성
  - [x] 푸터 생성
- [x] 회원가입 페이지 디자인
- [x] 아이콘 추가 (피그마에서 다운받아 사용)
