### ISSUE TITLE
[design] 쿠폰 등록 페이지 레이아웃

### ISSUE THREAD

**Issue by ovoxiix** [CoolPeace-yanolza/frontend#9]
## Description
피그마를 기준으로 쿠폰 등록 페이지에서 완성된 UI부터 마크업을 진행할 예정입니다.

<img width="865" alt="image" src="https://github.com/CoolPeace-yanolza/frontend/assets/155057856/3d6792ba-2da2-44d0-8def-5c50fbe6648e">

## Todo
- [x] 페이지 레이아웃 마크업
- [x] 스텝퍼 구현
- [x] 정보 입력 단계 마크업
- [x] 유형 선택 단계 마크업
- [x] 조건 선택 단계 마크업
- [x] 노출 기간 선택 단계 마크업
