### ISSUE TITLE
[modify] 전체 레이아웃 에러 및 로딩화면 개선

### ISSUE THREAD

**Issue by JitHoon** [CoolPeace-yanolza/frontend#92]
## Description

 전체 레이아웃 에러 및 로딩화면을 개선할 예정입니다.

## Todo

- [x] 레이아웃 에러 UI 변경
- [x] 레이아웃 로딩화면 개선
- [x] nav 이동 시 사이드 바 접기
