### ISSUE TITLE
[feat] Toast 구현 /  리스트 목록 위치 조정

### ISSUE THREAD

**Issue by jinjoo-jung** [CoolPeace-yanolza/frontend#98]
## Description
토글 on/of 와 쿠폰 삭제에서 사용되는 토스트 구현 예정입니다

## Todo

- [ ] 토글 on/off 시 토스트 띄우도록 (안에 실행취소까지)
- [ ] 쿠폰 삭제시 토스트 
- [ ] 객실 리스트 목록 보여주기에서 화면 하단 위치에따라서 리스트 위치가 달라지게
